[lint]
select = [
  "E",
  "F",
  "I",
  "UP",
  "B"
]
ignore = [
  "E501"
]

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
