[lint]
select = ["E", "F", "I", "N", "UP", "B", "Q"]
ignore = ["E203", "E266", "E501"]

[lint.isort]
known-first-party = ["scripts"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
